from pathlib import Path
import hashlib,json,difflib,subprocess,datetime,ast
root=Path(__file__).parent;repo=Path('/workspace/agenteam');snap=root/'snapshot';base='be0bd07b1dc1fcd91ad217c9bdbfe5a14003ce74';paths=json.loads((root/'paths.json').read_text());frozen=json.loads((root/'production-review-02/manifest.json').read_text())
for row in frozen['files']:
 assert hashlib.sha256((snap/row['path']).read_bytes()).hexdigest()==row['sha256']
 assert (repo/row['path']).read_bytes()==(snap/row['path']).read_bytes()
closure=json.loads((root/'inputs/fixed-closure.json').read_text());immutable=[]
for row in closure['files']:
 if row['path'] in paths:continue
 actual=hashlib.sha256((snap/row['path']).read_bytes()).hexdigest();assert actual==row['sha256'],row['path'];immutable.append({'path':row['path'],'sha256':actual})
dest=root/'candidate-freeze-01';dest.mkdir();entries=[];patch=[]
for rel in paths:
 data=(snap/rel).read_bytes();target=dest/'files'/rel;target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(data)
 active=repo/rel;active.parent.mkdir(parents=True,exist_ok=True);active.write_bytes(data)
 old=subprocess.run(['git','show',f'{base}:{rel}'],cwd=repo,stdout=subprocess.PIPE,stderr=subprocess.DEVNULL);original=old.stdout if old.returncode==0 else b''
 patch.extend(difflib.unified_diff(original.decode().splitlines(True),data.decode().splitlines(True),fromfile='a/'+rel if original else '/dev/null',tofile='b/'+rel))
 entries.append({'path':rel,'sha256':hashlib.sha256(data).hexdigest(),'bytes':len(data)})
(dest/'delta.patch').write_text(''.join(patch));(dest/'immutable-inputs.json').write_text(json.dumps({'baseline':base,'files':immutable,'account_embed_correction':'inputs/closure-asset-correction-01.json'},indent=2)+'\n')
m={'baseline':base,'spec_commit':'e81b029cd65fb26cc8598955e32b961dac35cb85','spec_sha256':'9413b70e0d524cc3223bf6aec9d1f761237ec22e96f988a99c9fa5e6827052b6','production_manifest':'production-review-02/manifest.json','production_manifest_sha256':'5cc06fdfd6961ce7f1e0150abd7a7b1b4b78bb4bfd86c51764417648668a836e','status':'all 20 files stopped; compile readiness only; no real PG run','frozen_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'paths':entries,'patch_sha256':hashlib.sha256((dest/'delta.patch').read_bytes()).hexdigest(),'immutable_inputs_sha256':hashlib.sha256((dest/'immutable-inputs.json').read_bytes()).hexdigest(),'checks':['review02-race-01','review02-vet-01','final-integration-compile-01','candidate-integration-compile-01','candidate-integration-vet-01','commands-build-01']}
(dest/'manifest.json').write_text(json.dumps(m,indent=2)+'\n');sha=hashlib.sha256((dest/'manifest.json').read_bytes()).hexdigest()
groups=[('new',['TestModelCurrentResolutionSelection','TestModelCurrentResolutionAtomicity','TestModelCurrentResolutionCanonicalLease','TestModelCurrentResolutionAuthorization','TestModelCurrentResolutionReplay','TestModelCurrentResolutionUnknown','TestModelCurrentResolutionSchema']),('old-model',['TestModelB01CRUDCurrentAuthorityAndCanonicalReplay','TestModelB01PlatformSelectionAndAtomicReplacement','TestModelB01SecretReferencesAndAllEffectsRollback','TestModelB01PreparedReferencesAndCurrentAdminAreRechecked','TestModelProjectSecretReferencesAndAtomicEffects','TestModelProjectPreparedAuthorizationAndReferenceMapping','TestModelProjectReceiptReadGateAndLegacySystemPlan','TestModelProjectAvailableDirectoryHasOnlyEnabledSafeUnion']),('secret',['TestSecretModelUsagePlannedReadAndAudit','TestSecretModelUsageRequestAndPlanIsolation','TestSecretModelUsageLockMappingAndRevocation','TestSecretModelUsageLegacyWrappersStayClosed','TestSecretModelUsageAuditWitnessAndNoMaterial','TestSecretModelUsageOutcomeAndCurrentValue','TestSecretBindingsAuthorizationAndReadAuditBoundary']),('account',['TestAccountUsagePlansCannotBeForgedDowngradedOrBypassed','TestAccountReadWaitsExactCurrentUserGateAndRejectsRevocation','TestAccountAuditFailureRollsBackLoginAndDestroysUnconfirmedRead','TestAccountExpiredLinkInvalidWhileActualMaterialUserKeepsLease'])]
ready={'input_manifest':'candidate-freeze-01/manifest.json','input_sha256':sha,'state':'ready compile; Docker permission pending; original fixture only','groups':[],'GOFLAGS':'-mod=readonly -buildvcs=false -p=2 -v','driver_budget':'unchanged -race -count=1 -timeout=6m','protocol':'stop on first nonzero group; preserve input/log/argv/exit; exact 4 containers+3 networks all nonce labels collected live and twice absent; existing 2 containers+4 networks unchanged; owned processes/gotmp/runtime empty before next group','P1':'TestModelCurrentResolutionUnknown/old-writer-completed-before-preflight-replans: normal Store candidate read barrier, real original final commit, formal Model/Provider delete, same writer preflight Busy then immutable replay','P2':'TestModelCurrentResolutionSchema/empty-actor-matching-digest and /wrong-canonical-unit: real bad durable facts plus matching scalar digest, reject canonical reuse; not an exploit claim','Unknown':'formal CommitResult decoration after actual real commit/rollback; record original returned attempt/cause and actual DB outcome; no network ACK or rollback-holding claim','static_findings':'review01 P1/P2 were static; do not describe them as dynamic original reds'}
for name,tops in groups:
 selector='^('+'|'.join(tops)+')$';ready['groups'].append({'name':name,'expected_top':tops,'top_count':len(tops),'selector':selector,'argv':['sh','scripts/test-objects.sh','-run',selector],'expected_containers':4,'expected_networks':3})
(root/'ready-selectors.json').write_text(json.dumps(ready,indent=2)+'\n')
observer=Path('/workspace/agenteam-system-model-root-author-7jypt_ik/run_fixture_02.py').read_text().replace('SYSTEM_MODEL_ROOT_FIXTURE_AUTHORIZED','CURRENT_MODEL_RESOLUTION_FIXTURE_AUTHORIZED').replace('ready-selectors-02.json','ready-selectors.json')
(root/'run_fixture.py').write_text(observer);ast.parse(observer)
print(json.dumps({'candidate':sha,'ready':hashlib.sha256((root/'ready-selectors.json').read_bytes()).hexdigest(),'observer':hashlib.sha256((root/'run_fixture.py').read_bytes()).hexdigest(),'count':len(entries),'immutable_fixed_count':len(immutable),'bytes':sum(e['bytes'] for e in entries)}))
