package account

import (
	"bytes"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"
	"sync"
	"testing"

	"github.com/LunaDeerTech/agenteam/internal/central/cursor"
	"github.com/LunaDeerTech/agenteam/internal/central/object"
	"github.com/LunaDeerTech/agenteam/internal/central/secret"
)

func testKey(b byte) string { return base64.StdEncoding.EncodeToString(bytes.Repeat([]byte{b}, 32)) }
func testRings(t *testing.T) (cursor.Keyring, secret.Keyring, object.DownloadKeyring) {
	t.Helper()
	c, e := cursor.LoadKeyring(fmt.Sprintf(`{"format":1,"current_kid":"p2","keys":[{"kid":"p1","key_b64":%q},{"kid":"p2","key_b64":%q}]}`, testKey(1), testKey(2)))
	if e != nil {
		t.Fatal(e)
	}
	s, e := secret.LoadKeyring(fmt.Sprintf(`{"format":1,"current_version":"2","keys":[{"version":"1","key_b64":%q},{"version":"2","key_b64":%q}]}`, testKey(3), testKey(4)), c)
	if e != nil {
		t.Fatal(e)
	}
	d, e := object.LoadDownloadKeyring(fmt.Sprintf(`{"format":1,"current_kid":"d2","keys":[{"kid":"d1","key_b64":%q},{"kid":"d2","key_b64":%q}]}`, testKey(5), testKey(6)), c, s)
	if e != nil {
		t.Fatal(e)
	}
	return c, s, d
}
func testKeys(t *testing.T) Keyring {
	t.Helper()
	c, s, d := testRings(t)
	k, e := LoadKeyring(fmt.Sprintf(`{"format":1,"current_kid":"a2","keys":[{"kid":"a1","key_b64":%q},{"kid":"a2","key_b64":%q}]}`, testKey(7), testKey(8)), c, s, d)
	if e != nil {
		t.Fatal(e)
	}
	return k
}
func TestAccountKeyringStrictAndPurposeSeparated(t *testing.T) {
	c, s, d := testRings(t)
	raw := fmt.Sprintf(`{"format":1,"current_kid":"a","keys":[{"kid":"a","key_b64":%q}]}`, testKey(7))
	bad := []string{"null", raw + `{}`, strings.Replace(raw, `"format":1`, `"format":1,"format":1`, 1), strings.Replace(raw, `"format":1`, `"format":null`, 1), strings.Replace(raw, `"keys":`, `"KEYS":`, 1), strings.Replace(raw, `"kid":"a"`, `"kid":null`, 1), strings.Replace(raw, `"kid":"a"`, `"kid":"a","extra":0`, 1), strings.Replace(raw, testKey(7), strings.TrimSuffix(testKey(7), "="), 1)}
	for b := byte(1); b <= 6; b++ {
		bad = append(bad, strings.Replace(raw, testKey(7), testKey(b), 1))
	}
	for _, b := range bad {
		if _, e := LoadKeyring(b, c, s, d); e == nil {
			t.Fatal("invalid ring accepted")
		}
	}
	k := testKeys(t)
	got, e := k.mac("a1", "command-v1", []byte("action"), []byte("a\x00b"), []byte("c"))
	if e != nil {
		t.Fatal(e)
	}
	// Independent Python stdlib hmac/struct vector, not generated by this implementation.
	if hex.EncodeToString(got) != "21e8fb2d7d3aa70185ee8c87f552d9ff68c8aba104a6c992f1f7cb1377f627ee" {
		t.Fatal("HMAC encoding vector")
	}
	if e := k.check("a1", "command-v1", got, []byte("action"), []byte("a\x00b"), []byte("c")); e != nil {
		t.Fatal(e)
	}
	if e := k.check("a1", "csrf-v1", got, []byte("action"), []byte("a\x00b"), []byte("c")); e == nil {
		t.Fatal("cross purpose")
	}
	if e := k.check("a1", "command-v1", got, []byte("action"), []byte("a"), []byte("\x00bc")); e == nil {
		t.Fatal("ambiguous tuple")
	}
	if _, e := k.mac("missing", "command-v1"); e == nil {
		t.Fatal("missing old kid")
	}
	var out bytes.Buffer
	for _, v := range []any{k, &k, struct{ k Keyring }{k}, struct{ x any }{k}} {
		for _, f := range []string{"%v", "%+v", "%#v", "%s", "%q"} {
			fmt.Fprintf(&out, f, v)
		}
		b, _ := json.Marshal(v)
		out.Write(b)
		slog.New(slog.NewTextHandler(&out, nil)).Info("key", "v", v)
	}
	for _, b := range []byte{7, 8} {
		if strings.Contains(out.String(), testKey(b)) || strings.Contains(out.String(), string(bytes.Repeat([]byte{b}, 32))) {
			t.Fatal("key leaked")
		}
	}
	before := k.current()
	if json.Unmarshal([]byte(raw), &k) == nil || k.current() != before {
		t.Fatal("JSON manufacture")
	}
	var group sync.WaitGroup
	for range 16 {
		group.Go(func() {
			for range 100 {
				if k.check("a1", "command-v1", got, []byte("action"), []byte("a\x00b"), []byte("c")) != nil {
					t.Error("concurrent key read")
				}
			}
		})
	}
	group.Wait()
}
