import pathlib,json,hashlib
r=pathlib.Path('/workspace/scratch/go-dependency-recovery');e=r/'evidence';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
commands={p.name:json.loads(p.read_text()) for p in sorted(e.glob('*.meta.json'))}
assert all('exit_code' in m and not pathlib.Path('/proc',str(m['pid'])).exists() for m in commands.values())
for n in ['download-required','install-fixed','offline-usage-list','offline-all-list','offline-integration-list','check-final-cache-02']:assert commands[n+'.meta.json']['exit_code']==0
inputs=json.loads((e/'input-and-missing.json').read_text());installation=json.loads((e/'cache-installation.json').read_text());after=json.loads((e/'availability-input-after.json').read_text());assert not after['changed_paths']
result={'status':'dependency availability restored','baseline':inputs['main'],'cache':'/workspace/go/pkg/mod','required_modules':31,'newly_completed_modules':25,'module_checks':'All 31 fixed required module ZIP, extracted source, and go.mod h1 values match project go.sum.','injection':'GOMODCACHE=/workspace/go/pkg/mod','go_mod_sha256':inputs['go.mod'],'go_sum_sha256':inputs['go.sum'],'created_files':installation['created_files'],'created_bytes':installation['created_bytes'],'created_path_content_sha256':installation['created_path_content_sha256'],'offline_list_records':{n:len((e/(n+'.raw')).read_text().splitlines()) for n in ['offline-all-list','offline-integration-list']},'commands':{n:{k:m[k] for k in ['exit_code','elapsed_seconds','raw_sha256','pid','starttime']} for n,m in commands.items()},'all_recorded_pids_absent':True,'availability_input_changes':after['changed_paths'],'limitations':['Dependency listing only: no builds, tests, fixture services, listeners or containers were started.','Listing consumed main175694bf plus the five Usage A worktree inputs recorded by hash; this is not product acceptance.','Only fixed project required modules missing complete caches were downloaded. Existing unrelated cache entries were not copied or rewritten.'],'preserved_failure':'First custom source-hash check used Python Path component ordering. Diagnostic showed equal ZIP/source file sets and bytes; changed to Go-compatible full relative-name string ordering and all 31 passed.'}
(e/'recovery-result.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
(r/'README.md').write_text('''# Go dependency recovery\n\nFixed project dependencies are available through `GOMODCACHE=/workspace/go/pkg/mod`. The project requires 31 modules; 25 incomplete entries were downloaded at their existing versions and verified against go.sum before adding only missing cache files. All 31 ZIP, extracted-source and go.mod h1 checks passed. Existing file bytes and version lists were preserved. Project go.mod/go.sum were unchanged.\n\nOffline `go list -deps -test` passed for Account/Usage HTTP, all ordinary packages, and all integration-tag packages. This establishes dependency availability only. Inputs are main175694bf plus the five Usage A worktree paths bound in evidence/availability-input-before.json; their hashes did not change during the checks. No product build/test or runtime fixture was executed.\n\nEvidence includes every command, required Go environment, raw output, exit, PID/starttime, original missing list, checksum results, new cache paths and a record of the corrected diagnostic sorting error. All nine recorded command processes have exited. The earlier MinIO recovery remains independently frozen.\n''')
paths=[*sorted(r.glob('*.py')),r/'README.md',r/'missing-arguments.json',*sorted(e.iterdir())]
manifest={str(p.relative_to(r)):sha(p) for p in paths if p.is_file() and p.name not in ['output-manifest.json','output-manifest.sha256']};(e/'output-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n');digest=sha(e/'output-manifest.json');(e/'output-manifest.sha256').write_text(digest+'  output-manifest.json\n')
assert all(sha(r/p)==s for p,s in manifest.items());print(json.dumps({'manifest_entries':len(manifest),'manifest_sha256':digest,'recorded_commands':len(commands),'newly_completed_modules':25,'fixed_required_modules_verified':31,'offline_lists':'all 3 passed','input_changes':after['changed_paths']},indent=2))
