package model

import (
	"context"
	"encoding/json"
	"strings"
	"testing"
	"time"

	ac "github.com/LunaDeerTech/agenteam/internal/central/audit/contract"
	"github.com/LunaDeerTech/agenteam/internal/central/cursor"
	f "github.com/LunaDeerTech/agenteam/internal/central/foundation"
	id "github.com/LunaDeerTech/agenteam/internal/central/identity/contract"
	mc "github.com/LunaDeerTech/agenteam/internal/central/model/contract"
	"github.com/LunaDeerTech/agenteam/internal/central/postgres"
	sc "github.com/LunaDeerTech/agenteam/internal/central/secret/contract"
	"github.com/jackc/pgx/v5"
)

func TestModelProjectCommandNamespacesPreserveOldSystemBytes(t *testing.T) {
	uid, _ := f.ParseID[id.User]("01900000-0000-7000-8000-000000000001")
	sid, _ := f.ParseID[id.Session]("01900000-0000-7000-8000-000000000002")
	actor, _ := id.NewHuman(uid, sid)
	r := commandRequest{Meta: mc.CommandMeta{Actor: actor, Scope: id.SystemScope(), Key: "fixture-key"}, Kind: "provider.create", ProviderInput: &mc.ProviderInput{Name: "original", Protocol: mc.OpenAIChat, BaseURL: "https://provider.example/v1", Enabled: true, Options: json.RawMessage(`{}`)}}
	// Literal pre-Project anonymous-struct bytes, not generated by new code.
	old := []byte(`{"Format":"model-command-v1","User":"01900000-0000-7000-8000-000000000001","Kind":"provider.create","Resource":"","Provider":"","Expected":"0","ProviderInput":{"Name":"original","Protocol":"openai-chat-completions","BaseURL":"https://provider.example/v1","Enabled":true,"CredentialID":"","Options":{}},"ModelInput":null,"Selection":null,"Replacement":""}`)
	want, _ := cursor.Digest(old)
	got, err := commandSemantic(r)
	if err != nil || got != want {
		t.Fatal("System semantic bytes changed", err)
	}
	ci, err := commandIdentity(r.Meta, r.Kind)
	if err != nil || ci.Canonical() != `{"namespace":"model.system","owner_ids":["01900000-0000-7000-8000-000000000001"],"command":"provider.create","key":"fixture-key"}` {
		t.Fatal("System original identity changed")
	}
	project := mustID[id.Project](t)
	r.Meta.Scope, _ = id.InProject(project)
	one, err := commandSemantic(r)
	if err != nil || one == want {
		t.Fatal("Project semantic not isolated")
	}
	pi, _ := commandIdentity(r.Meta, r.Kind)
	if pi.Namespace() != "model.project" || strings.Join(pi.OwnerIDs(), ",") != project.String()+","+uid.String() {
		t.Fatal("Project stable owners reordered")
	}
	r.Meta.Actor, _ = id.NewHuman(uid, mustID[id.Session](t))
	two, _ := commandSemantic(r)
	pj, _ := commandIdentity(r.Meta, r.Kind)
	if two != one || pj.Canonical() != pi.Canonical() {
		t.Fatal("renewed Session changed canonical command")
	}
	r.Meta.Scope, _ = id.InProject(mustID[id.Project](t))
	three, _ := commandSemantic(r)
	pk, _ := commandIdentity(r.Meta, r.Kind)
	if three == one || pk.Canonical() == pi.Canonical() {
		t.Fatal("cross Project receipt collision")
	}
}
func scopeCommandRow(r *commandRecord) postgres.Row {
	return scanFunc(func(out ...any) error {
		if r == nil {
			return pgx.ErrNoRows
		}
		*out[0].(*string) = r.ID
		*out[1].(*string) = r.Identity
		*out[2].(*string) = r.User
		*out[3].(*string) = r.Kind
		*out[4].(*string) = r.Resource
		*out[5].(*string) = r.Phase
		*out[6].(*f.Digest) = r.Semantic
		*out[7].(*[]byte), _ = json.Marshal(r.Plan)
		*out[8].(*[]byte), _ = json.Marshal(r.Receipt)
		return nil
	})
}
func TestModelProjectReceiptAndUnknownUseReadAndExactScope(t *testing.T) {
	actor := testActor(t)
	project := mustID[id.Project](t)
	scope, _ := id.InProject(project)
	meta := mc.CommandMeta{Actor: actor, Scope: scope, Key: "same-key"}
	identity, _ := commandIdentity(meta, "model.update")
	semantic := hash([]byte("original"))
	receipt := mc.CommandReceipt{Kind: "model.update", ResourceID: mustID[mc.Model](t).String(), Version: 2}
	row := &commandRecord{ID: mustID[struct{}](t).String(), Identity: identity.Canonical(), User: actor.Details().UserID, Kind: "model.update", Resource: receipt.ResourceID, Phase: "committed", Semantic: semantic, Receipt: &receipt, Plan: mutationPlan{Project: project.String(), Semantic: semantic, Receipt: receipt, Metadata: ac.ModelMetadataFields{Version: 2, ChangedFields: []string{"name"}}}}
	st := &projectScopeStore{}
	st.row = func(q string, args ...any) postgres.Row {
		if !strings.Contains(q, "scope='project' AND project_id=$2") || len(args) != 2 || args[1] != project.String() {
			t.Fatal("Project load omitted actual scope predicate")
		}
		return scopeCommandRow(row)
	}
	calls := 0
	revoked := false
	a := projectPureAuthority(t, st, projectGrantFunc(func(_ context.Context, _ f.Tx, a id.Actor, p id.ProjectID, i id.AccessIntent) (id.AccessGrant, error) {
		calls++
		if i != id.Read {
			t.Fatal("receipt attempted new mutation permission")
		}
		if revoked {
			return id.AccessGrant{}, fault(f.SessionRevoked)
		}
		return projectGrant(a, p, i)
	}))
	s, err := New(st, a, testDependencies(t))
	if err != nil {
		t.Fatal(err)
	}
	cause, _ := f.NewCommandsCause(identity)
	original := f.UnknownResult(mustID[f.TransactionAttempt](t), cause)
	got, err := s.replayScope(context.Background(), actor, scope, identity, semantic, &original)
	if err != nil || got != receipt {
		t.Fatal("exact Unknown receipt", err)
	}
	got, err = s.recheckPreparationScope(context.Background(), actor, scope, identity, semantic, fault(f.VersionConflict))
	if err != nil || got != receipt {
		t.Fatal("preparation failure preceded receipt", err)
	}
	row.Semantic = hash([]byte("different"))
	_, err = s.replayScope(context.Background(), actor, scope, identity, semantic, &original)
	requireCode(t, err, f.IdempotencyKeyReused)
	row.Semantic = semantic
	revoked = true
	_, err = s.replayScope(context.Background(), actor, scope, identity, semantic, &original)
	requireCode(t, err, f.CommitUnknown)
	revoked = false
	row.Plan.Project = ""
	_, err = s.replayScope(context.Background(), actor, scope, identity, semantic, nil)
	requireCode(t, err, f.DependencyUnavailable)
	row = nil
	_, err = s.replayScope(context.Background(), actor, scope, identity, semantic, &original)
	requireCode(t, err, f.CommitUnknown)
	if calls < 5 {
		t.Fatal("confirmation skipped current authority")
	}
}
func TestModelProjectViewsPolicyAndPrivateFactsCarryScope(t *testing.T) {
	project := mustID[id.Project](t)
	scope, _ := id.InProject(project)
	cid := mustID[sc.Credential](t)
	ref, _ := sc.NewCredentialRef(cid, scope)
	now, _ := f.NewInstant(time.Now())
	record := providerRecord{Project: project.String(), ID: mustID[mc.Provider](t).String(), Input: providerInput{Name: "Project", Protocol: mc.OpenAIChat, BaseURL: "https://provider.example/v1", CredentialID: cid.String(), Options: json.RawMessage(`{}`)}, Version: 1, CreatedAt: now, UpdatedAt: now}
	v, err := record.view()
	if err != nil || !v.Scope.Equal(scope) || !v.Input.CredentialRef.Equal(ref) {
		t.Fatal("Provider lost actual scope", err)
	}
	if err = providerPolicyScope(v.Input, scope); err != nil {
		t.Fatal(err)
	}
	requireCode(t, providerPolicy(v.Input), f.Forbidden)
	other, _ := id.InProject(mustID[id.Project](t))
	requireCode(t, providerPolicyScope(v.Input, other), f.Forbidden)
	actor := testActor(t)
	meta := mc.CommandMeta{Actor: actor, Scope: scope, Key: "fact"}
	identity, _ := commandIdentity(meta, "provider.create")
	p := mutationPlan{Project: project.String(), Identity: identity.Canonical(), Kind: "provider.create", Resource: record.ID, AfterProvider: &record, Metadata: ac.ModelMetadataFields{ProviderID: record.ID, Version: 1, ChangedFields: []string{"created"}}}
	entry, _, err := auditEntry(actor, &p)
	if err != nil || !entry.Fields().Scope.Equal(scope) {
		t.Fatal("Audit lost Project scope", err)
	}
	prepared := &preparedCommand{actor: actor, plan: p}
	request := sc.UsageRequest{Actor: actor, Ref: ref, Purpose: sc.Model, ReferenceOwner: record.ID, Action: sc.RetainReferenceUsage, Retain: true}
	if !referenceMatches(prepared, request) {
		t.Fatal("real Provider reference not planned")
	}
	request.Ref, _ = sc.NewCredentialRef(cid, id.SystemScope())
	if referenceMatches(prepared, request) {
		t.Fatal("same UUID accepted different credential scope")
	}
}
